### PR TITLE
Commits from 2021-2022

### PR DESCRIPTION
**Pull request by Marie-Donnie**

### CODE REVIEW

**Comment by rcherrueau** [comment]
Hi @Marie-Donnie, long time no see!

I am pretty sure I merged something like this in December 2021.  IMHO, only the last 6 commit should be merged. 

Could you rebase your repository on master to resolve this?

**Comment by Marie-Donnie** [comment]
Hey, you'll probably have some news from me soon if I'm not too long to finish my manuscript ;)

I see that there are actually not a lot of meaningful commits, and you're right, most of it was already pushed; I'm doing a better PR, sorry!

**Comment by msimonin** [comment]
Hi there !
Just jumping in for fun :)

**Comment by rcherrueau** [comment]
> Hey, you'll probably have some news from me soon if I'm not too long to finish my manuscript ;)

I am pleased to see that you keep on!

> Hi there !
> Just jumping in for fun :)

Look what the cat dragged in! It's been a while :smiley_cat:

**Comment by Marie-Donnie** [comment]
Happy to _see_ the both of you :smile: !

**Pull request closed without merging**
